matrix:
  include:
    - language: java
      cache:
        directories:
          - $HOME/.m2
    - language: node_js
      cache: npm
      node_js:
        - "9"
      install:
        - cd src/angular-fe
        - npm install
      script:
        - npm run build
        #- npm run lint
